import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  Shield,
  Key,
  CheckCircle,
  AlertTriangle,
  Hash,
  User,
  Clock,
} from 'lucide-react';
import { GeneratedDocument, VerificationResult } from '@/types/regulatory';

interface SignatureVerificationProps {
  document: GeneratedDocument;
  verification: VerificationResult;
}

export function SignatureVerification({ document, verification }: SignatureVerificationProps) {
  return (
    <Card className="bg-gradient-to-br from-purple-50 via-blue-50 to-indigo-50 border-2 border-purple-200">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-purple-900">
          <Shield className="h-5 w-5" />
          Cryptographic Signatures
        </CardTitle>
        <p className="text-sm text-purple-700">
          Ed25519 digital signatures with FIPS 186-4 compliance
        </p>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Content Hash */}
        <div className="bg-white rounded-lg p-4 border border-purple-200">
          <div className="flex items-center gap-2 mb-2">
            <Hash className="h-4 w-4 text-purple-600" />
            <div className="font-semibold text-gray-900">Content Hash (SHA-256)</div>
          </div>
          <div className="font-mono text-xs bg-gray-100 p-3 rounded break-all">
            {document.content_hash}
          </div>
          <div className="text-xs text-gray-600 mt-2">
            Every character of the document is hashed to ensure integrity
          </div>
        </div>

        {/* Generated Signature */}
        <div className="bg-white rounded-lg p-4 border-l-4 border-green-500">
          <div className="flex items-start justify-between mb-3">
            <div className="flex items-center gap-2">
              <Key className="h-4 w-4 text-green-600" />
              <div className="font-semibold text-gray-900">Generated By</div>
            </div>
            <Badge variant="outline" className="bg-green-100 text-green-800 border-green-300">
              Ed25519
            </Badge>
          </div>

          <div className="space-y-2">
            <div>
              <div className="text-xs text-gray-600 mb-1">User ID:</div>
              <div className="font-mono text-xs bg-gray-100 p-2 rounded break-all">
                {document.generated_by}
              </div>
            </div>

            <div>
              <div className="text-xs text-gray-600 mb-1">Digital Signature:</div>
              <div className="font-mono text-xs bg-gray-100 p-2 rounded break-all">
                {document.generated_signature}
              </div>
            </div>

            <div className="flex items-center gap-2 text-xs text-gray-600">
              <Clock className="h-3 w-3" />
              {new Date(document.created_at).toLocaleString()}
            </div>
          </div>

          <div className="mt-3 p-2 bg-green-50 rounded border border-green-200">
            <div className="text-xs text-green-800">
              <strong>Algorithm:</strong> Ed25519 (FIPS 186-4) - Elliptic Curve Digital Signature
            </div>
          </div>
        </div>

        {/* Approved Signature (if exists) */}
        {document.approved_signature && document.approved_by && (
          <div className="bg-white rounded-lg p-4 border-l-4 border-blue-500">
            <div className="flex items-start justify-between mb-3">
              <div className="flex items-center gap-2">
                <CheckCircle className="h-4 w-4 text-blue-600" />
                <div className="font-semibold text-gray-900">Approved By</div>
              </div>
              <Badge variant="outline" className="bg-blue-100 text-blue-800 border-blue-300">
                Ed25519
              </Badge>
            </div>

            <div className="space-y-2">
              <div>
                <div className="text-xs text-gray-600 mb-1">User ID:</div>
                <div className="font-mono text-xs bg-gray-100 p-2 rounded break-all">
                  {document.approved_by}
                </div>
              </div>

              <div>
                <div className="text-xs text-gray-600 mb-1">Approval Signature:</div>
                <div className="font-mono text-xs bg-gray-100 p-2 rounded break-all">
                  {document.approved_signature}
                </div>
              </div>

              {document.approved_at && (
                <div className="flex items-center gap-2 text-xs text-gray-600">
                  <Clock className="h-3 w-3" />
                  {new Date(document.approved_at).toLocaleString()}
                </div>
              )}
            </div>
          </div>
        )}

        {/* Verification Status */}
        <div
          className={`p-4 rounded-lg border-2 ${
            verification.overall_valid
              ? 'bg-green-100 border-green-500'
              : 'bg-red-100 border-red-500'
          }`}
        >
          {verification.overall_valid ? (
            <>
              <div className="flex items-center gap-2 text-green-800 font-bold mb-2">
                <CheckCircle className="h-5 w-5" />
                CRYPTOGRAPHICALLY VERIFIED
              </div>
              <div className="text-sm text-green-700">
                This document's signatures and blockchain chain have been mathematically verified.
                Any tampering would be immediately detectable through broken chain hashes and invalid signatures.
              </div>
              <div className="mt-3 grid grid-cols-2 gap-2 text-xs">
                <div className="flex items-center gap-1">
                  <CheckCircle className="h-3 w-3 text-green-600" />
                  <span className="text-green-800">Ed25519 Signatures Valid</span>
                </div>
                <div className="flex items-center gap-1">
                  <CheckCircle className="h-3 w-3 text-green-600" />
                  <span className="text-green-800">Blockchain Chain Valid</span>
                </div>
                <div className="flex items-center gap-1">
                  <CheckCircle className="h-3 w-3 text-green-600" />
                  <span className="text-green-800">Content Hash Match</span>
                </div>
                <div className="flex items-center gap-1">
                  <CheckCircle className="h-3 w-3 text-green-600" />
                  <span className="text-green-800">Audit Ledger Intact</span>
                </div>
              </div>
            </>
          ) : (
            <>
              <div className="flex items-center gap-2 text-red-800 font-bold mb-2">
                <AlertTriangle className="h-5 w-5" />
                VERIFICATION FAILED
              </div>
              <div className="text-sm text-red-700">
                One or more cryptographic verifications have failed. This document may have been tampered with.
              </div>
              <div className="mt-3 space-y-1 text-xs">
                <div className="flex items-center gap-1">
                  {verification.signature_valid ? (
                    <CheckCircle className="h-3 w-3 text-green-600" />
                  ) : (
                    <AlertTriangle className="h-3 w-3 text-red-600" />
                  )}
                  <span className={verification.signature_valid ? 'text-green-800' : 'text-red-800'}>
                    Ed25519 Signatures: {verification.signature_valid ? 'Valid' : 'Invalid'}
                  </span>
                </div>
                <div className="flex items-center gap-1">
                  {verification.ledger_valid ? (
                    <CheckCircle className="h-3 w-3 text-green-600" />
                  ) : (
                    <AlertTriangle className="h-3 w-3 text-red-600" />
                  )}
                  <span className={verification.ledger_valid ? 'text-green-800' : 'text-red-800'}>
                    Blockchain Chain: {verification.ledger_valid ? 'Valid' : 'Broken'}
                  </span>
                </div>
              </div>
            </>
          )}

          <div className="mt-3 pt-3 border-t border-opacity-30">
            <div className="text-xs text-gray-700">
              <strong>Verified at:</strong> {new Date(verification.verified_at).toLocaleString()}
            </div>
          </div>
        </div>

        {/* Security Explanation */}
        <Alert className="bg-purple-100 border-purple-300">
          <Shield className="h-4 w-4 text-purple-600" />
          <AlertDescription className="text-purple-900 text-sm">
            <strong>How It Works:</strong> Ed25519 uses elliptic curve cryptography to create unforgeable digital
            signatures. Each signature is unique to the document content and the signer's private key. Combined with
            blockchain-style chain hashing, this provides non-repudiation and tamper-evidence for regulatory compliance.
          </AlertDescription>
        </Alert>
      </CardContent>
    </Card>
  );
}
