-- AI Assistant Features: Natural Language Query & Inquiry Assistant
-- Migration: 005
-- Created: 2025-01-11

-- ============================================================================
-- Natural Language Query System
-- ============================================================================

-- Query history and results
CREATE TABLE IF NOT EXISTS nl_query_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    query_text TEXT NOT NULL CHECK (char_length(query_text) > 0),
    generated_sql TEXT,
    validated_sql TEXT,
    execution_time_ms INTEGER,
    result_count INTEGER,
    result_data JSONB,
    ai_cost_usd DECIMAL(10,6) NOT NULL DEFAULT 0,
    ai_tokens_used INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(50) NOT NULL CHECK (status IN ('success', 'failed', 'invalid_sql', 'quota_exceeded')),
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_nl_query_user ON nl_query_sessions(user_id);
CREATE INDEX idx_nl_query_created ON nl_query_sessions(created_at DESC);
CREATE INDEX idx_nl_query_status ON nl_query_sessions(status);

COMMENT ON TABLE nl_query_sessions IS 'Tracks natural language queries converted to SQL';
COMMENT ON COLUMN nl_query_sessions.query_text IS 'Original natural language query from user';
COMMENT ON COLUMN nl_query_sessions.generated_sql IS 'Raw SQL generated by AI';
COMMENT ON COLUMN nl_query_sessions.validated_sql IS 'Validated and sanitized SQL with user_id filter injected';
COMMENT ON COLUMN nl_query_sessions.result_data IS 'Cached query results (limited to 100 rows)';

-- Saved/favorite queries for quick access
CREATE TABLE IF NOT EXISTS nl_query_favorites (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    query_text TEXT NOT NULL CHECK (char_length(query_text) > 0),
    description TEXT,
    category VARCHAR(100), -- 'inventory', 'transactions', 'analytics', etc.
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, query_text)
);

CREATE INDEX idx_nl_favorites_user ON nl_query_favorites(user_id);

-- ============================================================================
-- Inquiry Assistant System
-- ============================================================================

-- AI-generated suggestions for inquiry responses
CREATE TABLE IF NOT EXISTS inquiry_ai_suggestions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    inquiry_id UUID NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    suggestion_type VARCHAR(50) NOT NULL CHECK (suggestion_type IN (
        'initial_response',
        'negotiation',
        'pricing_adjustment',
        'terms_clarification',
        'closing_deal',
        'follow_up',
        'rejection'
    )),
    suggestion_text TEXT NOT NULL CHECK (char_length(suggestion_text) > 0),
    context_snapshot JSONB, -- Inquiry state when suggestion was made
    ai_reasoning TEXT, -- Why AI suggested this response
    ai_cost_usd DECIMAL(10,6) NOT NULL DEFAULT 0,
    ai_tokens_used INTEGER NOT NULL DEFAULT 0,
    was_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    was_edited BOOLEAN NOT NULL DEFAULT FALSE,
    final_message_id UUID REFERENCES inquiry_messages(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_ai_suggestions_inquiry ON inquiry_ai_suggestions(inquiry_id);
CREATE INDEX idx_ai_suggestions_user ON inquiry_ai_suggestions(user_id);
CREATE INDEX idx_ai_suggestions_type ON inquiry_ai_suggestions(suggestion_type);
CREATE INDEX idx_ai_suggestions_accepted ON inquiry_ai_suggestions(was_accepted) WHERE was_accepted = TRUE;

COMMENT ON TABLE inquiry_ai_suggestions IS 'AI-powered response suggestions for marketplace inquiries';
COMMENT ON COLUMN inquiry_ai_suggestions.context_snapshot IS 'Snapshot of inquiry, product, and market data used for suggestion';
COMMENT ON COLUMN inquiry_ai_suggestions.ai_reasoning IS 'AI explanation of why this response was suggested';
COMMENT ON COLUMN inquiry_ai_suggestions.was_accepted IS 'Whether user sent this suggestion (possibly after editing)';

-- ============================================================================
-- Update User AI Usage Limits (extend existing table)
-- ============================================================================

-- Add quotas for new features
ALTER TABLE user_ai_usage_limits
ADD COLUMN IF NOT EXISTS monthly_nl_query_limit INTEGER NOT NULL DEFAULT 100,
ADD COLUMN IF NOT EXISTS monthly_nl_queries_used INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS monthly_inquiry_assist_limit INTEGER NOT NULL DEFAULT 200,
ADD COLUMN IF NOT EXISTS monthly_inquiry_assists_used INTEGER NOT NULL DEFAULT 0;

COMMENT ON COLUMN user_ai_usage_limits.monthly_nl_query_limit IS 'Maximum natural language queries per month';
COMMENT ON COLUMN user_ai_usage_limits.monthly_nl_queries_used IS 'Natural language queries used this period';
COMMENT ON COLUMN user_ai_usage_limits.monthly_inquiry_assist_limit IS 'Maximum inquiry assistant suggestions per month';
COMMENT ON COLUMN user_ai_usage_limits.monthly_inquiry_assists_used IS 'Inquiry assistant suggestions used this period';

-- ============================================================================
-- Helper Functions
-- ============================================================================

-- Function to check if user has NL query quota available
CREATE OR REPLACE FUNCTION check_nl_query_quota(p_user_id UUID)
RETURNS BOOLEAN AS $$
DECLARE
    v_limit INTEGER;
    v_used INTEGER;
BEGIN
    SELECT monthly_nl_query_limit, monthly_nl_queries_used
    INTO v_limit, v_used
    FROM user_ai_usage_limits
    WHERE user_id = p_user_id;

    IF NOT FOUND THEN
        -- No limits set, allow (defaults will be created on first use)
        RETURN TRUE;
    END IF;

    RETURN v_used < v_limit;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to check if user has inquiry assistant quota available
CREATE OR REPLACE FUNCTION check_inquiry_assist_quota(p_user_id UUID)
RETURNS BOOLEAN AS $$
DECLARE
    v_limit INTEGER;
    v_used INTEGER;
BEGIN
    SELECT monthly_inquiry_assist_limit, monthly_inquiry_assists_used
    INTO v_limit, v_used
    FROM user_ai_usage_limits
    WHERE user_id = p_user_id;

    IF NOT FOUND THEN
        RETURN TRUE;
    END IF;

    RETURN v_used < v_limit;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
